# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

after-login-command = [
  # 'exec-and-forget borders active_color=0xFFC591FF inactive_color=0x00494D64 width=5.0 hidpi=on',
]

after-startup-command = []

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"
automatically-unhide-macos-hidden-apps = true

#####################################################################################################
#                                            Window Stuff                                           #
#####################################################################################################
[gaps]
inner.horizontal = 14
inner.vertical = 14
outer.left = 17
outer.bottom = 17
outer.top = 17
outer.right = 17

[mode.main.binding]
cmd-alt-h = []
shift-ctrl-h = 'focus left'
shift-ctrl-j = 'focus down'
shift-ctrl-k = 'focus up'
shift-ctrl-l = 'focus right'
shift-ctrl-minus = 'macos-native-minimize'
shift-ctrl-q = 'close'
cmd-shift-h = 'move-node-to-workspace prev'
cmd-shift-l = 'move-node-to-workspace next'

#####################################################################################################
#                                            workspaces                                             #
#####################################################################################################
#============ first monitor workspaces
cmd-1 = 'workspace 1:Browser'
cmd-2 = 'workspace 2:Editor'
cmd-3 = 'workspace 3:Sims/VMs'
cmd-4 = 'workspace 4:Tools'
cmd-5 = 'workspace 5:Media'
cmd-6 = 'workspace 6:Misc'

#============ second monitor workspaces
cmd-7 = 'workspace 7:MT2/Browser'
cmd-8 = 'workspace 8:MT2/Editor'

[workspace-to-monitor-force-assignment]
"1:Browser" = 'main'
"2:Editor" = 'main'
"3:Sims/VMs" = 'main'
"4:Tools" = 'main'
"5:Media" = 'main'
"6:Misc" = 'main'
"7:MT2/Browser" = 'secondary'
"8:MT2/Editor" = 'secondary'

cmd-l = 'workspace next'
cmd-h = 'workspace prev'

alt-shift-right = 'move-workspace-to-monitor --wrap-around next'
alt-shift-left = 'move-workspace-to-monitor --wrap-around prev'

#####################################################################################################
#                                            Mode resize                                            #
#####################################################################################################
shift-ctrl-r = 'mode resize'
[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
b = 'balance-sizes'
enter = 'mode main'
esc = 'mode main'
ctrl-leftSquareBracket = 'mode main'

#####################################################################################################
#                                            Callbacks                                              #
#####################################################################################################
#============================================= Browsers =============================================
#============ First Monitor
[[on-window-detected]]
if.app-id = 'org.freedownloadmanager.fdm6'
run = ["layout floating", "move-node-to-workspace 1:Browser"]

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = ["move-node-to-workspace 1:Browser"]

#============ Second Monitor
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = ["move-node-to-workspace 7:MT2/Browser"]

#============================================= Editors/IDEs =========================================
#============ First Monitor
[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = "move-node-to-workspace 2:Editor"

[[on-window-detected]]
if.app-id = 'com.google.android.studio'
run = "move-node-to-workspace 2:Editor"

[[on-window-detected]]
if.app-id = 'com.apple.dt.Xcode'
run = ["move-node-to-workspace 2:Editor"]

#============ Second Monitor
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ["move-node-to-workspace 8:MT2/Editor"]

#============================================= Sims/Vms =============================================
[[on-window-detected]]
if.app-name-regex-substring = 'qemu-system-aarch64'
run = ["layout floating", "move-node-to-workspace 3:Sims/VMs"]

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = ["layout floating"]

[[on-window-detected]]
if.app-name-regex-substring = 'raycast'
run = ["layout floating"]

[[on-window-detected]]
if.app-id = 'com.apple.iphonesimulator'
run = ["layout floating", "move-node-to-workspace 3:Sims/VMs"]

#============================================= Tools ================================================
[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = "move-node-to-workspace 4:Tools"

[[on-window-detected]]
if.app-id = 'com.postmanlabs.mac'
run = ["move-node-to-workspace 4:Tools"]

#============================================= Media =============================================
[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = "move-node-to-workspace 5:Media"

[[on-window-detected]]
if.app-id = 'org.videolan.vlc'
run = "move-node-to-workspace 5:Media"

[[on-window-detected]]
if.app-id = 'com.smartcodeltd.stremio'
run = "move-node-to-workspace 5:Media"

#============================================= Misc =============================================
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = "move-node-to-workspace 6:Misc"

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = "move-node-to-workspace 6:Misc"

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = "move-node-to-workspace 6:Misc"

# [[on-window-detected]]
# if.app-id = 'com.raycast.macos'
# run = ["layout floating", "move-node-to-workspace 6:Misc"]

[[on-window-detected]]
if.app-id = 'ch.protonvpn.mac'
run = "move-node-to-workspace 6:Misc"

[[on-window-detected]]
if.app-id = 'com.grammarly.ProjectLlama'
run = ["layout floating", "move-node-to-workspace 6:Misc"]
