# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

after-login-command = []
after-startup-command = []
exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'accordion'
default-root-container-orientation = 'vertical'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"
automatically-unhide-macos-hidden-apps = true

#####################################################################################################
#                                            Window Stuff                                           #
#####################################################################################################
accordion-padding = 20

[gaps]
inner.horizontal = 14
inner.vertical = 14
outer.left = 17
outer.bottom = 17
outer.top = [{ monitor.'built-in.*' = 13 }, 17]
outer.right = 17

[key-mapping]
preset = 'qwerty'

[mode.main.binding]
#####################################################################################################
#                                            Windows                                                #
#####################################################################################################
shift-ctrl-h = 'focus left'
shift-ctrl-j = 'focus down'
shift-ctrl-k = 'focus up'
shift-ctrl-l = 'focus right'
shift-ctrl-minus = 'macos-native-minimize'
shift-ctrl-q = 'close'
cmd-shift-h = 'move-node-to-workspace prev --focus-follows-window'
cmd-shift-l = 'move-node-to-workspace next --focus-follows-window'

#####################################################################################################
#                                            workspaces                                             #
#####################################################################################################
#============ first monitor workspaces
cmd-0 = 'workspace Browser'
cmd-1 = 'workspace Editor'
cmd-2 = 'workspace Sims/VMs'
cmd-3 = 'workspace Tools'
cmd-4 = 'workspace Media'
cmd-5 = 'workspace Misc'
cmd-6 = 'workspace Social'
#============ second monitor workspaces
# cmd-7 = 'workspace MT2/Browser'
# cmd-8 = 'workspace MT2/Editor'
# cmd-9 = 'workspace MT2/VMs'
# cmd-0 = 'workspace MT2/Tools'

cmd-l = 'workspace next'
cmd-h = 'workspace prev'

alt-shift-right = 'move-workspace-to-monitor --wrap-around next'
alt-shift-left = 'move-workspace-to-monitor --wrap-around prev'

[workspace-to-monitor-force-assignment]
"Browser" = 'main'
"Editor" = 'main'
"Sims/VMs" = 'main'
"Tools" = 'main'
"Media" = 'main'
"Misc" = 'main'
"Social" = 'main'
# "MT2/Browser" = 'secondary'
# "MT2/Editor" = 'secondary'
# "MT2/VMs" = 'secondary'
# "MT2/Tools" = 'secondary'

#####################################################################################################
#                                            Mode resize                                            #
#####################################################################################################
# shift-ctrl-r = 'mode resize'
# [mode.resize.binding]
# h = 'resize width -50'
# j = 'resize height +50'
# k = 'resize height -50'
# l = 'resize width +50'
# b = 'balance-sizes'
# enter = 'mode main'
# esc = 'mode main'
# ctrl-leftSquareBracket = 'mode main'

#####################################################################################################
#                                            Callbacks                                              #
#####################################################################################################
#============================================= Browsers =============================================
#============ First Monitor
[[on-window-detected]]
if.app-id = 'org.freedownloadmanager.fdm6'
run = ["layout floating", "move-node-to-workspace Browser"]

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = ["move-node-to-workspace Browser"]

#============ Second Monitor
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = ["move-node-to-workspace Browser"]

#============================================= Editors/IDEs =========================================
#============ First Monitor
[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = "move-node-to-workspace Editor"

[[on-window-detected]]
if.app-id = 'com.google.android.studio'
run = "move-node-to-workspace Editor"

[[on-window-detected]]
if.app-id = 'com.apple.dt.Xcode'
run = ["move-node-to-workspace Editor"]

# [[on-window-detected]]
# if.app-id = 'com.microsoft.VSCode'
# run = ["move-node-to-workspace Editor"]
#
#============ Second Monitor


#============================================= Sims/Vms =============================================
#============ First Monitor
[[on-window-detected]]
if.app-name-regex-substring = 'qemu-system-aarch64'
run = ["layout floating", "move-node-to-workspace Sims/VMs"]

[[on-window-detected]]
if.app-id = 'com.apple.iphonesimulator'
run = ["layout floating", "move-node-to-workspace Sims/VMs"]

#============ Second Monitor
[[on-window-detected]]
if.app-name-regex-substring = 'UTM'
run = ["layout floating", "move-node-to-workspace Sims/VMs"]

#============================================= Tools ================================================
#============ First Monitor
[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = "move-node-to-workspace Tools"

[[on-window-detected]]
if.app-id = 'com.postmanlabs.mac'
run = ["move-node-to-workspace Tools"]

[[on-window-detected]]
if.app-id = "com.github.GitHubClient"
run = ["move-node-to-workspace Tools"]

[[on-window-detected]]
if.app-id = "org.gimp.gimp-3.0"
run = ["move-node-to-workspace Tools"]

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = ["layout floating", "move-node-to-workspace Tools"]
#============ Second Monitor

#============================================= Media =============================================
[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = "move-node-to-workspace Media"

[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = "move-node-to-workspace Media"

[[on-window-detected]]
if.app-id = 'com.jpochyla.psst'
run = "move-node-to-workspace Media"

[[on-window-detected]]
if.app-id = 'org.videolan.vlc'
run = "move-node-to-workspace Media"

[[on-window-detected]]
if.app-id = 'com.smartcodeltd.stremio'
run = "move-node-to-workspace Media"

#============================================= Misc =============================================
[[on-window-detected]]
if.app-id = 'com.bitwarden.desktop'
run = ["move-node-to-workspace Misc"]

[[on-window-detected]]
if.app-id = 'com.openai.chat'
run = "move-node-to-workspace Misc"


[[on-window-detected]]
if.app-id = "net.freemacsoft.AppCleaner"
run = ["layout floating"]

[[on-window-detected]]
if.app-id = "md.obsidian"
run = ["move-node-to-workspace Misc"]

[[on-window-detected]]
if.app-id = "com.apple.AppStore"
run = ["move-node-to-workspace Misc"]

#============================================= Social =============================================
#============ First Monitor
[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = "move-node-to-workspace Social"

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = "move-node-to-workspace Social"

[[on-window-detected]]
if.app-id = 'app.legcord.Legcord'
run = "move-node-to-workspace Social"

[[on-window-detected]]
if.app-id = "net.whatsapp.WhatsApp"
run = "move-node-to-workspace Social"

[[on-window-detected]]
if.app-id = "com.apple.mail"
run = "move-node-to-workspace Social"
#============ Second Monitor


#============================================= Detached (Floating) =============================================
[[on-window-detected]]
if.app-id = 'org.pqrs.Karabiner-Elements.Settings'
run = ["layout floating"]

[[on-window-detected]]
if.app-id = 'com.apple.Preview'
run = ["layout floating"]

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ["layout floating", "move-node-to-workspace Tools"]

[[on-window-detected]]
if.app-name-regex-substring = 'raycast'
run = ["layout floating"]

[[on-window-detected]]
if.app-id = 'ch.protonvpn.mac'
run = ["layout floating"]

[[on-window-detected]]
if.app-id = "com.tunnelbear.mac.TunnelBear"
run = ["layout floating"]

[[on-window-detected]]
if.app-id = 'com.grammarly.ProjectLlama'
run = ["layout floating"]

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ["layout floating", "move-node-to-workspace Editor"]
