[manager]
show_symlink = true
show_hidden = true

[opener]
docs = [
  { run = 'zathura "$@"', orphan = true, for = "unix", desc = "Docs Viewer" },
]
image = [
  { run = 'feh --scale-down --image-bg "#282A36" --hide-pointer "$@"', orphan = true, for = "unix", desc = "Image Viewer" },
]
edit = [{ run = 'nvim "$@"', block = true }]
play = [{ run = 'mpv "$@"', orphan = true, for = "unix" }]
open = [{ run = 'xdg-open "$@"', desc = "Open" }]

[open]
rules = [
  { mime = "video/*", use = "play" },
  { mime = "application/json", use = "edit" },
  { mime = "text/*", use = "edit" },
  { name = "*.html", use = "edit" },
  { mime = "application/pdf", use = "docs" },
  { mime = "image/*", use = "image" },
]
