[mgr]
show_symlink = true
show_hidden = true

[plugin]
prepend_previewers = [
  { name = "*.csv", run = "rich-preview" },
  { name = "*.md", run = "rich-preview" },
  { name = "*.rst", run = "rich-preview" },
  { name = "*.ipynb", run = "rich-preview" },
  { name = "*.json", run = "rich-preview" },
  #    { name = "*.lang_type", run = "rich-preview"} # for particular language files eg. .py, .go., .lua, etc.
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
]
prepend_preloaders = [
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
]

[opener]
docs = [
  { run = 'zathura "$@"', orphan = true, for = "unix", desc = "Docs Viewer" },
]
image = [
  { run = 'feh --scale-down --image-bg "#282A36" --hide-pointer "$@"', orphan = true, for = "linux", desc = "Image Viewer" },
  { run = 'open "$@"', orphan = true, for = "macos", desc = "Image Viewer" },
]
edit = [{ run = 'nvim "$@"', block = true }]
play = [{ run = 'mpv "$@"', orphan = true, for = "unix" }]
open = [
  { run = 'xdg-open "$@"', for = "linux", desc = "Open" },
  { run = 'open "$@"', for = "macos", desc = "Open" },
]

[open]
rules = [
  { mime = "video/*", use = "play" },
  { mime = "application/json", use = "edit" },
  { mime = "text/*", use = "edit" },
  { name = "*.html", use = "edit" },
  { mime = "application/pdf", use = "docs" },
  { mime = "image/*", use = "image" },
]
