-- spoon.SpoonInstall:andUse("Seal", {
-- 	hotkeys = {
-- 		show = {
-- 			{ "cmd" },
-- 			"space",
-- 		},
-- 	},
-- 	fn = function(s)
-- 		s:loadPlugins({
-- 			"apps",
-- 			"calc",
-- 		})
-- 		s:refreshAllCommands()
-- 	end,
-- 	start = true,
-- })
