################################################################################
#                                    HELIX                                     #
################################################################################

###################
# THEME           #
###################
theme = "dracula"

###################
# CONFIG          #
###################
[editor]
clipboard-provider = "pasteboard"
true-color = true
undercurl = true
color-modes = true
cursorline = true
# bufferline = "always"
indent-heuristic = "hybrid"
line-number = "absolute"
cursorcolumn = true
auto-completion = true
auto-format = true
auto-info = true
popup-border = "all"
auto-pairs = true
end-of-line-diagnostics = "hint"
gutters = ["diff", "diagnostics", "line-numbers", "spacer", "spacer"]

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true
auto-signature-help = true
display-signature-help-docs = true
display-progress-messages = true
snippets = true
goto-reference-include-declaration = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
  "version-control",
]
center = []
right = ["diagnostics", "workspace-diagnostics", "file-type"]

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-global = false

[keys.normal]
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"
y = [":clipboard-yank", ":redraw"]
"C-s" = ":w"
X = ["extend_line_up", "extend_to_line_bounds"]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
C-d = ["half_page_down", "align_view_center"]
C-u = ["half_page_up", "align_view_center"]

[keys.insert]
j = { j = "normal_mode" }
"C-s" = ":w"

[keys.select]
esc = ["collapse_selection", "normal_mode"]
d = [":clipboard-yank", "delete_selection"]
p = ":clipboard-paste-replace"
y = [":clipboard-yank", ":redraw"]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
X = ["extend_line_up", "extend_to_line_bounds"]

# [keys.normal.space]
# ","      = ["save_selection", "goto_line_end", ":append-output echo ','", "collapse_selection", "delete_selection", "jump_backward"]
# ";"      = ["save_selection", "goto_line_end", ":append-output echo ';'", "collapse_selection", "delete_selection", "jump_backward"]

[keys.normal.space.c]
l = ":o ~/.config/helix/languages.toml"
o = ":config-open"
r = ":config-reload"

[keys.normal.space.q]
q = ":qa"
